from __future__ import annotations

from enum import Enum
from pathlib import Path
from types import NoneType
from typing import Any, get_args, get_origin

from pydantic import BaseModel

from agent_harness_contracts import (
    CancelRunResponse,
    CreateRunRequest,
    CreateRunResponse,
    ListRunsResponse,
    RunEvent,
    RunRecord,
    RunStatus,
    TokenUsage,
)


OUTPUT_PATH = (
    Path(__file__).resolve().parents[3] / "apps" / "web" / "lib" / "generated" / "contracts.ts"
)
ENUMS = [RunStatus]
MODELS = [
    TokenUsage,
    CreateRunRequest,
    RunRecord,
    RunEvent,
    CreateRunResponse,
    ListRunsResponse,
    CancelRunResponse,
]


def render_type(annotation: Any) -> str:
    origin = get_origin(annotation)
    if origin is None:
        if annotation is Any:
            return "unknown"
        if annotation is str:
            return "string"
        if annotation in {int, float}:
            return "number"
        if annotation is bool:
            return "boolean"
        if annotation is NoneType:
            return "null"
        if isinstance(annotation, type) and issubclass(annotation, BaseModel):
            return annotation.__name__
        if isinstance(annotation, type) and issubclass(annotation, Enum):
            return annotation.__name__
        raise TypeError(f"Unsupported annotation: {annotation!r}")

    if origin in {list, tuple, set}:
        item_type = render_type(get_args(annotation)[0])
        return f"{item_type}[]"

    if origin is dict:
        key_type, value_type = get_args(annotation)
        if key_type is not str:
            raise TypeError(f"Unsupported dict key type: {annotation!r}")
        rendered_value = render_type(value_type)
        if rendered_value == "unknown":
            return "Record<string, unknown>"
        return f"Record<string, {rendered_value}>"

    if origin in {NoneType, type(None)}:
        return "null"

    if getattr(origin, "__name__", "") == "UnionType" or str(origin) == "typing.Union":
        members = [render_type(member) for member in get_args(annotation)]
        ordered = [member for member in members if member != "null"]
        if "null" in members:
            ordered.append("null")
        return " | ".join(dict.fromkeys(ordered))

    raise TypeError(f"Unsupported annotation origin: {annotation!r}")


def render_enum(enum_type: type[Enum]) -> str:
    const_name = f"{enum_type.__name__[0].lower()}{enum_type.__name__[1:]}Values"
    values = ",\n  ".join(f'"{member.value}"' for member in enum_type)
    return "\n".join(
        [
            f"export const {const_name} = [",
            f"  {values},",
            "] as const;",
            "",
            f"export type {enum_type.__name__} = (typeof {const_name})[number];",
        ]
    )


def render_model(model_type: type[BaseModel]) -> str:
    lines = [f"export interface {model_type.__name__} {{"]
    for name, field in model_type.model_fields.items():
        lines.append(f"  {name}: {render_type(field.annotation)};")
    lines.append("}")
    return "\n".join(lines)


def build_output() -> str:
    sections = [
        "// This file is generated by packages/contracts/scripts/generate_frontend_types.py.",
        "// Do not edit it by hand.",
    ]
    sections.extend(render_enum(enum_type) for enum_type in ENUMS)
    sections.extend(render_model(model_type) for model_type in MODELS)
    return "\n\n".join(sections) + "\n"


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(build_output(), encoding="utf-8")


if __name__ == "__main__":
    main()
