"""Tests for process-based isolation in IsolatedExecutor."""
from __future__ import annotations

import multiprocessing as mp
from typing import Any

import pytest
from agent_harness_contracts import CreateRunRequest, RunStatus
from agent_harness_core import InMemoryRunStore, IsolatedExecutor, ResourceLimits
from agent_harness_worker.main import WorkerConfig, run_once


def test_isolated_executor_completes_run_in_subprocess() -> None:
    """Verify that a run completes successfully when executed in an isolated subprocess."""
    store = InMemoryRunStore()
    run = store.create_run(CreateRunRequest(input="isolated execution test"))
    resource_limits = ResourceLimits(cpu_seconds=60, memory_mb=256)

    executor = IsolatedExecutor(store, resource_limits=resource_limits)
    result = executor.execute(run)

    assert result.status == RunStatus.COMPLETED
    assert result.output is not None
    assert result.output["response"] == "Echo: isolated execution test"

    # Verify events were persisted
    events = store.list_events(run.run_id)
    event_types = [event.event_type for event in events]
    assert "workflow.started" in event_types
    assert "workflow.completed" in event_types
    assert "run.completed" in event_types


def test_isolated_executor_without_limits_uses_same_process() -> None:
    """When resource_limits is None, execution should happen in the same process."""
    store = InMemoryRunStore()
    run = store.create_run(CreateRunRequest(input="no isolation test"))

    executor = IsolatedExecutor(store, resource_limits=None)
    result = executor.execute(run)

    assert result.status == RunStatus.COMPLETED
    assert result.output is not None
    assert result.output["response"] == "Echo: no isolation test"


def test_resource_limits_apply_correctly() -> None:
    """Test that ResourceLimits.apply() sets rlimits correctly."""
    import resource

    limits = ResourceLimits(cpu_seconds=60, memory_mb=128)

    # We can't actually test apply() in the main process because it would
    # affect the test runner, but we can verify the values are correct
    assert limits.cpu_seconds == 60
    assert limits.memory_mb == 128


def test_worker_with_process_isolation_completes_run() -> None:
    """Test that the worker correctly uses IsolatedExecutor when isolation is enabled."""
    store = InMemoryRunStore()
    run = store.create_run(CreateRunRequest(input="worker isolation test"))

    config = WorkerConfig(
        poll_interval_seconds=0.0,
        lease_seconds=30,
        worker_id="worker-isolation-test",
        enable_process_isolation=True,
        cpu_limit_seconds=60,
        memory_limit_mb=256,
    )

    resource_limits = ResourceLimits(
        cpu_seconds=config.cpu_limit_seconds,
        memory_mb=config.memory_limit_mb,
    )
    executor = IsolatedExecutor(store, resource_limits=resource_limits)

    did_work = run_once(store, executor, config)

    assert did_work is True
    completed = store.get_run(run.run_id)
    assert completed is not None
    assert completed.status == RunStatus.COMPLETED


def test_worker_without_process_isolation_completes_run() -> None:
    """Test that the worker works correctly when isolation is disabled."""
    store = InMemoryRunStore()
    run = store.create_run(CreateRunRequest(input="worker no isolation test"))

    config = WorkerConfig(
        poll_interval_seconds=0.0,
        lease_seconds=30,
        worker_id="worker-no-isolation-test",
        enable_process_isolation=False,
    )

    executor = IsolatedExecutor(store, resource_limits=None)

    did_work = run_once(store, executor, config)

    assert did_work is True
    completed = store.get_run(run.run_id)
    assert completed is not None
    assert completed.status == RunStatus.COMPLETED


def test_events_are_relayed_from_subprocess() -> None:
    """Verify that events generated in the subprocess are relayed to the store."""
    store = InMemoryRunStore()
    run = store.create_run(CreateRunRequest(input="event relay test"))
    resource_limits = ResourceLimits(cpu_seconds=60, memory_mb=256)

    executor = IsolatedExecutor(store, resource_limits=resource_limits)
    executor.execute(run)

    events = store.list_events(run.run_id)

    # Check for key events that should have been relayed
    # Note: run.started is generated by the worker when claiming, not by executor
    event_types = [event.event_type for event in events]
    expected_events = [
        "run.created",
        "run.queued",
        "workflow.started",
        "node.started",
        "tool.started",
        "tool.completed",
        "node.completed",
        "model.started",
        "model.completed",
        "workflow.completed",
        "run.completed",
    ]

    for expected in expected_events:
        assert expected in event_types, f"Missing event: {expected}"


def test_subprocess_failure_handling() -> None:
    """Test that subprocess failures are handled gracefully."""
    from agent_harness_core.isolated_executor import SubprocessEvent

    # Create a queue and a run
    event_queue: mp.Queue = mp.Queue()
    store = InMemoryRunStore()
    run = store.create_run(CreateRunRequest(input="failure test"))

    # Test that we can put and get events from the queue
    test_event = SubprocessEvent(
        event_type="test.event",
        category="test",
        payload={"test": True},
    )
    event_queue.put(test_event)

    # Verify the event can be retrieved
    queued_event = event_queue.get(timeout=1.0)
    assert isinstance(queued_event, SubprocessEvent)
    assert queued_event.event_type == "test.event"

    # Clean up
    event_queue.close()
    event_queue.join_thread()


def test_multiple_runs_dont_interfere() -> None:
    """Test that multiple runs can execute without interfering with each other."""
    store = InMemoryRunStore()
    resource_limits = ResourceLimits(cpu_seconds=60, memory_mb=256)
    executor = IsolatedExecutor(store, resource_limits=resource_limits)

    run1 = store.create_run(CreateRunRequest(input="first run"))
    run2 = store.create_run(CreateRunRequest(input="second run"))

    result1 = executor.execute(run1)
    result2 = executor.execute(run2)

    assert result1.status == RunStatus.COMPLETED
    assert result1.output["response"] == "Echo: first run"

    assert result2.status == RunStatus.COMPLETED
    assert result2.output["response"] == "Echo: second run"

    # Verify events are separate
    events1 = store.list_events(run1.run_id)
    events2 = store.list_events(run2.run_id)

    assert all(e.run_id == run1.run_id for e in events1)
    assert all(e.run_id == run2.run_id for e in events2)


def test_model_output_preserved_through_isolation() -> None:
    """Verify model output details are preserved when running in isolation."""
    store = InMemoryRunStore()
    run = store.create_run(CreateRunRequest(input="model output test"))
    resource_limits = ResourceLimits(cpu_seconds=60, memory_mb=256)

    executor = IsolatedExecutor(store, resource_limits=resource_limits)
    result = executor.execute(run)

    assert result.status == RunStatus.COMPLETED
    assert result.output is not None

    model_output = result.output.get("model")
    assert model_output is not None
    assert model_output["provider"] == "demo"
    assert model_output["model_name"] == "demo-echo-model"
    assert "usage" in model_output
    assert "latency_ms" in model_output
    assert model_output["request_id"] == "demo-echo"
